package com.vatsytech.ui;

import com.vatsytech.office.ExcelCell;
import com.vatsytech.office.OfficeUtils;
import java.awt.Cursor;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ComparisonFrame extends javax.swing.JFrame {
    
    File fA,fB;

    /**
     * Creates new form StartComparisonFrame
     */
    public ComparisonFrame() {
        initComponents();
        try{
        fA = new File("A.xlsx");
        fB = new File("B.xlsx");        
        initDropList(fA,jSheetFileA);
        initDropList(fB,jSheetFileB);
        }
        catch(Exception ex){
            Logger.getLogger(ComparisonFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFileA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFileB = new javax.swing.JTextField();
        jCompareButton = new javax.swing.JButton();
        jButtonFileA = new javax.swing.JButton();
        jButtonFileB = new javax.swing.JButton();
        messageLabel = new java.awt.Label();
        jSheetFileA = new java.awt.Choice();
        jSheetFileB = new java.awt.Choice();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cell Comparison Tool");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        textFileA.setText("A.xlsx");

        jLabel1.setText("File A");

        jLabel2.setText("File B");

        textFileB.setText("B.xlsx");

        jCompareButton.setText("Compare");
        jCompareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompareButtonActionPerformed(evt);
            }
        });

        jButtonFileA.setText("...");
        jButtonFileA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileAActionPerformed(evt);
            }
        });

        jButtonFileB.setText("...");
        jButtonFileB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileBActionPerformed(evt);
            }
        });

        messageLabel.setForeground(new java.awt.Color(255, 51, 51));
        messageLabel.setText("   ");

        jSheetFileA.setEnabled(false);

        jSheetFileB.setEnabled(false);

        jLabel3.setText("Build 0.0.2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCompareButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSheetFileA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFileA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFileA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSheetFileB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFileB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFileB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFileA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonFileA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSheetFileA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFileB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFileB))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSheetFileB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jCompareButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileAActionPerformed
        messageLabel.setText("");
        try{            
        FileChooser a=new FileChooser(this,true,fA);
        a.setVisible(true);
        fA=a.getFile();        
        textFileA.setText(fA.getName());       
        initDropList(fA,jSheetFileA);
        }        catch(Exception e){
            e.printStackTrace();
            System.out.println("File exception while choosing file A");
            jSheetFileA.removeAll();
            jSheetFileA.setEnabled(false);
            messageLabel.setText("Please select .xlsx files");
        }
    }//GEN-LAST:event_jButtonFileAActionPerformed

    private void jButtonFileBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileBActionPerformed
        messageLabel.setText("");
        try{            
        FileChooser a=new FileChooser(this,true,fB);
        a.setVisible(true);
        fB=a.getFile();        
        textFileB.setText(fB.getName());
        initDropList(fB,jSheetFileB);
        }        catch(Exception e){
            System.out.println("File exception while choosing file B");
            jSheetFileB.removeAll();
            jSheetFileB.setEnabled(false);
            messageLabel.setText("Please select .xlsx files");
        }
    }//GEN-LAST:event_jButtonFileBActionPerformed

    private void jCompareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompareButtonActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        messageLabel.setText("");
        if(fA==null || fB==null){
            messageLabel.setText("Please select .xlsx files");
        }
        else{
            //System.out.println("Starting");
            try {                
                ExcelCell[][] resA=OfficeUtils.getInstance().compareFiles(fA,jSheetFileA.getSelectedIndex(), fB,jSheetFileB.getSelectedIndex());
                ResultFrame res=new ResultFrame(resA);
                //this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));                
                res.setVisible(true);
                res.setTitle(fA.getName()+"["+jSheetFileA.getSelectedItem()+"]"+" VS "+fB.getName()+"["+jSheetFileB.getSelectedItem()+"]");
                res.setjLabelFileAText(fA.getName()+"["+jSheetFileA.getSelectedItem()+"]");
                res.setjLabelFileBText(fB.getName()+"["+jSheetFileB.getSelectedItem()+"]");
                
                System.gc();
            } catch (Exception ex) {
                Logger.getLogger(ComparisonFrame.class.getName()).log(Level.SEVERE, null, ex);
                //this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                this.pack();
                messageLabel.setText("Please select .xlsx files");
            }
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 
    }//GEN-LAST:event_jCompareButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparisonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparisonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparisonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparisonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComparisonFrame().setVisible(true);
            }
        });
    }
    
    private void initDropList (File fA,java.awt.Choice j) throws Exception{
        String[] lSheet=OfficeUtils.getInstance().getSheetNamesFromXlsx(fA);
        j.removeAll();
        for(int i=0;i<lSheet.length;i++){
            j.add(lSheet[i]);
        }      
        j.setEnabled(true);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFileA;
    private javax.swing.JButton jButtonFileB;
    private javax.swing.JButton jCompareButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Choice jSheetFileA;
    private java.awt.Choice jSheetFileB;
    private java.awt.Label messageLabel;
    private javax.swing.JTextField textFileA;
    private javax.swing.JTextField textFileB;
    // End of variables declaration//GEN-END:variables
}
